---
name: Build and Publish

on:
  push:
    branches:
      - main

env:
  DOCKER_REGISTRY: ghcr.io/jonta-sancar/site-devopsdays

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Github Registrey
        if: success()
        uses: docker/login-action@v1
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: docker build -t ${{ env.DOCKER_REGISTRY }}:latest .

      - name: Publish image
        run: docker push ${{ env.DOCKER_REGISTRY }}:latest